spring:
  application:
    name: SPRING-CLOUD-GATEWAY

  cloud:
    gateway:
      routes:
        - id: authentication_service_route
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/authentication-service/api/**
          filters:
            - StripPrefix=1

        - id: items_service_route
          uri: lb://ITEMS-SERVICE
          predicates:
            - Path=/items-service/api/**
          filters:
            - StripPrefix=1

        - id: cart_service_route
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart-service/api/**
          filters:
            - StripPrefix=1

        - id: payment_service_route
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/api/**
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
